-- CRIANDO UM TABELA 
CREATE TABLE banco_itau_usuarios (
    id INTEGER,
    nome TEXT,
    idade INTEGER,
)

-- INSERINDO UM NA TABELA;
INSERT INTO( id, nome, idade) -- PROPRIEDADES A SER MODIFICADAS.
VALUES(1, 'Paulo Silva', 26), -- VALORES A SEREM REGISTRADOS.
    (2, 'Yamin Bianco', 4) -- ADICIONANDO MULTIPLOS VALORES BASTA DAR UM VIRGULA.

-- SELECIONANO UM VALOR DENTRO DA TABELA;
SELECT nome FROM banco_itau_usuarios; -- ELE VAI SELECIONAR OS NOME DENTRO DA TABELA banco_itau


-- ADICIONANDO UMA NOVA COLUNA NA TABELA;
ALTER TABLE banco_itau_usuarios
ADD COLUMN phone_number INTEGER -- AQUI VAMOS ESPECIFICAR O VALOR DA COLUNA A SER ADICIONADO E SEU TIPO;
SELECT * FROM banco_itau -- SOMENTE PARA CONFERIR;


-- ATUALIZANDO UMA PROPRIEDADE DA COLUNA
UPDATE banco_itau_usuarios  -- BANCO AO QUAL ELE VAI ESTAR REALIZANDO A ALTERAÇÂO;
SET  phone_number = 1199978145 -- QUAL INFORMAÇÂO ELE VAI SETAR;
WHERE   id = 1 -- ONDE ELE VAI ADICIONAR AS INFORMAÇÔES

-- DELETANDO VALORES DE UMA TABELA NO  BANCO DE DADOS;
DELETE FROM banco_itau_usuarios -- DELETE DA TABELA OS SEGUINTES VALORES;
WHERE nome IS 'Yasmin Bianco'; -- DELETANDO TODOS OS VALORES REFERENTE AO NOME YASMIN BIANCO.
SELECT * FROM banco_itau -- SOMENTE PARA CONFERIR;

CREATE TABLE banco_itau_usuarios (
    id INTEGER PRIMARY KEY, -- VALORES DE INDENTIFICAÇÂO UNICA;
    nome TEXT NOT NULL, -- VALOR NÂO PODE SER VAZIO.
    idade INTEGER NOT NULL, -- NÂO PODE SER VAZIO
    cpf INTEGER NOT NULL -- VALOR NÂO PODE SER VAZIO.
)

DELETE FROM banco_itau  -- ELE DELETARA DA TABELA;
WHERE nome  -- NOME DO USUARIO;
IN ('Yasmin Bianco') -- COM A SEGUINTE REFERENCIA;

DELETE FROM friends WHERE id IN (1);



